export const EVENT_ON_CREATE_REQUESTED = 'EVENT_ON_CREATE_REQUESTED';
export const EVENT_ON_CREATE_SUCCEEDED = 'EVENT_ON_CREATE_SUCCEEDED';
export const EVENT_ON_CREATE_FAILED = 'EVENT_ON_CREATE_FAILED';
