export const ON_CREATE_REQUESTED = 'ON_CREATE_REQUESTED';
export const ON_CREATE_SUCCEEDED = 'ON_CREATE_SUCCEEDED';
export const ON_CREATE_FAILED = 'ON_CREATE_FAILED';

export const ON_GET_ALL_BY_USER_ID_REQUESTED = 'ON_GET_ALL_BY_USER_ID_REQUESTED';
export const ON_GET_ALL_BY_USER_ID_SUCCEEDED = 'ON_GET_ALL_BY_USER_ID_SUCCEEDED';
export const ON_GET_ALL_BY_USER_ID_FAILED = 'ON_GET_ALL_BY_USER_ID_FAILED';

export const ON_GET_DETAILS_REQUESTED = 'ON_GET_DETAILS_REQUESTED';
export const ON_GET_DETAILS_SUCCEEDED = 'ON_GET_DETAILS_SUCCEEDED';
export const ON_GET_DETAILS_FAILED = 'ON_GET_DETAILS_FAILED';
