export const ON_CREATE_REQUESTED = 'ON_CREATE_REQUESTED';
export const ON_CREATE_SUCCEEDED = 'ON_CREATE_SUCCEEDED';
export const ON_CREATE_FAILED = 'ON_CREATE_FAILED';

export const ON_GET_ALL_BY_USER_ID_REQUESTED = 'ON_GET_ALL_BY_USER_ID_REQUESTED';
export const ON_GET_ALL_BY_USER_ID_SUCCEEDED = 'ON_GET_ALL_BY_USER_ID_SUCCEEDED';
export const ON_GET_ALL_BY_USER_ID_FAILED = 'ON_GET_ALL_BY_USER_ID_FAILED';

export const ON_GET_DETAILS_REQUESTED = 'ON_GET_DETAILS_REQUESTED';
export const ON_GET_DETAILS_SUCCEEDED = 'ON_GET_DETAILS_SUCCEEDED';
export const ON_GET_DETAILS_FAILED = 'ON_GET_DETAILS_FAILED';

export const ON_EDIT_REQUESTED = 'ON_EDIT_REQUESTED';
export const ON_EDIT_SUCCEEDED = 'ON_EDIT_SUCCEEDED';
export const ON_EDIT_FAILED = 'ON_EDIT_FAILED';

export const EVENT_DELETE_IMAGE = 'EVENT_DELETE_IMAGE';

export const EVENT_ON_CREATE_DRAFT_REQUESTED = 'EVENT_ON_CREATE_DRAFT_REQUESTED';
export const EVENT_ON_CREATE_DRAFT_SUCCEEDED = 'EVENT_ON_CREATE_DRAFT_SUCCEEDED';
export const EVENT_ON_CREATE_DRAFT_FAILED = 'EVENT_ON_CREATE_DRAFT_FAILED';
