export const USER_ON_LOGIN_REQUESTED = 'USER_ON_LOGIN_REQUESTED';
export const USER_ON_LOGIN_SUCCEEDED = 'USER_ON_LOGIN_SUCCEEDED';
export const USER_ON_LOGIN_FAILED = 'USER_ON_LOGIN_FAILED';

export const USER_ON_LOGOUT = 'USER_ON_LOGOUT';

export const USER_ON_REGISTER_REQUESTED = 'USER_ON_REGISTER_REQUESTED';
export const USER_ON_REGISTER_SUCCEEDED = 'USER_ON_REGISTER_SUCCEEDED';
export const USER_ON_REGISTER_FAILED = 'USER_ON_REGISTER_FAILED';
